### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by farahjr** [ionicthemes/ionic4-starter-app#6]
Cannot find module 'node-sass'

ng] i ｢wdm｣: wait until bundle finished: /
[ng]
[ng] Date: 2019-05-27T00:36:00.644Z
[ng] Hash: 542b7b36561f690384e9
[ng] Time: 9693ms
[ng]
[ng] ERROR in ./src/global.scss (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./node_modules/sass-loader/lib/loader.js??ref--14-3!./src/global.scss)
[ng] Module build failed (from ./node_modules/sass-loader/lib/loader.js):
[ng] Error: Cannot find module 'node-sass'

*******************************************************

Complete Log here:

PS D:\WS\Ionic\ionic4-starter-app> ionic serve
> ng run app:serve --host=0.0.0.0 --port=8100
[ng] ****************************************************************************************
[ng] This is a simple server for use in testing or debugging Angular applications locally.
[ng] It hasn't been reviewed for security issues.
[ng] DON'T USE IT FOR PRODUCTION!
[ng] ****************************************************************************************

[INFO] Development server running!

       Local: http://localhost:8100
       External: http://192.168.1.43:8100

       Use Ctrl+C to quit this process

[INFO] Browser window opened to http://localhost:8100!

[ng] i ｢wdm｣: wait until bundle finished: /
[ng]
[ng] Date: 2019-05-27T00:36:00.644Z
[ng] Hash: 542b7b36561f690384e9
[ng] Time: 9693ms
[ng]
[ng] ERROR in ./src/global.scss (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./node_modules/sass-loader/lib/loader.js??ref--14-3!./src/global.scss)
[ng] Module build failed (from ./node_modules/sass-loader/lib/loader.js):
[ng] Error: Cannot find module 'node-sass'
[ng] Require stack:
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\sass-loader\lib\loader.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\loader-runner\lib\loadLoader.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\loader-runner\lib\LoaderRunner.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\webpack\lib\NormalModule.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\webpack\lib\NormalModuleFactory.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\webpack\lib\Compiler.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\webpack\lib\webpack.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\@angular-devkit\build-webpack\src\webpack\index.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\@angular-devkit\build-webpack\src\index.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\@angular-devkit\build-angular\src\dev-server\index.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\@angular-devkit\architect\src\architect.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\@angular-devkit\architect\src\index.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\@angular\cli\models\architect-command.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\@angular\cli\commands\build-impl.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\@angular-devkit\schematics\tools\export-ref.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\@angular-devkit\schematics\tools\index.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\@angular\cli\utilities\json-schema.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\@angular\cli\models\command-runner.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\@angular\cli\lib\cli\index.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\@angular\cli\lib\init.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\@angular\cli\bin\ng
[ng]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
[ng]     at Function.Module._load (internal/modules/cjs/loader.js:527:27)
[ng]     at Module.require (internal/modules/cjs/loader.js:681:19)
[ng]     at require (internal/modules/cjs/helpers.js:16:16)
[ng]     at Object.sassLoader (D:\WS\Ionic\ionic4-starter-app\node_modules\sass-loader\lib\loader.js:46:72)
[ng] ERROR in ./src/theme/variables.scss (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./node_modules/sass-loader/lib/loader.js??ref--14-3!./src/theme/variables.scss)
[ng] Module build failed (from ./node_modules/sass-loader/lib/loader.js):
[ng] Error: Cannot find module 'node-sass'
[ng] Require stack:
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\sass-loader\lib\loader.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\loader-runner\lib\loadLoader.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\loader-runner\lib\LoaderRunner.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\webpack\lib\NormalModule.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\webpack\lib\NormalModuleFactory.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\webpack\lib\Compiler.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\webpack\lib\webpack.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\@angular-devkit\build-webpack\src\webpack\index.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\@angular-devkit\build-webpack\src\index.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\@angular-devkit\build-angular\src\dev-server\index.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\@angular-devkit\architect\src\architect.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\@angular-devkit\architect\src\index.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\@angular\cli\models\architect-command.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\@angular\cli\commands\build-impl.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\@angular-devkit\schematics\tools\export-ref.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\@angular-devkit\schematics\tools\index.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\@angular\cli\utilities\json-schema.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\@angular\cli\models\command-runner.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\@angular\cli\lib\cli\index.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\@angular\cli\lib\init.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\@angular\cli\bin\ng
[ng]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
[ng]     at Function.Module._load (internal/modules/cjs/loader.js:527:27)
[ng]     at Module.require (internal/modules/cjs/loader.js:681:19)
[ng]     at require (internal/modules/cjs/helpers.js:16:16)
[ng]     at Object.sassLoader (D:\WS\Ionic\ionic4-starter-app\node_modules\sass-loader\lib\loader.js:46:72)
[ng] ERROR in ./src/app/pages/new-item/new-item.page.scss
[ng] Module build failed (from ./node_modules/sass-loader/lib/loader.js):
[ng] Error: Cannot find module 'node-sass'
[ng] Require stack:
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\sass-loader\lib\loader.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\loader-runner\lib\loadLoader.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\loader-runner\lib\LoaderRunner.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\webpack\lib\NormalModule.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\webpack\lib\NormalModuleFactory.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\webpack\lib\Compiler.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\webpack\lib\webpack.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\@angular-devkit\build-webpack\src\webpack\index.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\@angular-devkit\build-webpack\src\index.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\@angular-devkit\build-angular\src\dev-server\index.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\@angular-devkit\architect\src\architect.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\@angular-devkit\architect\src\index.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\@angular\cli\models\architect-command.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\@angular\cli\commands\build-impl.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\@angular-devkit\schematics\tools\export-ref.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\@angular-devkit\schematics\tools\index.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\@angular\cli\utilities\json-schema.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\@angular\cli\models\command-runner.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\@angular\cli\lib\cli\index.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\@angular\cli\lib\init.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\@angular\cli\bin\ng
[ng]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
[ng]     at Function.Module._load (internal/modules/cjs/loader.js:527:27)
[ng]     at Module.require (internal/modules/cjs/loader.js:681:19)
[ng]     at require (internal/modules/cjs/helpers.js:16:16)
[ng]     at Object.sassLoader (D:\WS\Ionic\ionic4-starter-app\node_modules\sass-loader\lib\loader.js:46:72)
[ng] ERROR in ./src/app/pages/update-item/update-item.page.scss
[ng] Module build failed (from ./node_modules/sass-loader/lib/loader.js):
[ng] Error: Cannot find module 'node-sass'
[ng] Require stack:
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\sass-loader\lib\loader.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\loader-runner\lib\loadLoader.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\loader-runner\lib\LoaderRunner.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\webpack\lib\NormalModule.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\webpack\lib\NormalModuleFactory.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\webpack\lib\Compiler.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\webpack\lib\webpack.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\@angular-devkit\build-webpack\src\webpack\index.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\@angular-devkit\build-webpack\src\index.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\@angular-devkit\build-angular\src\dev-server\index.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\@angular-devkit\architect\src\architect.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\@angular-devkit\architect\src\index.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\@angular\cli\models\architect-command.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\@angular\cli\commands\build-impl.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\@angular-devkit\schematics\tools\export-ref.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\@angular-devkit\schematics\tools\index.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\@angular\cli\utilities\json-schema.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\@angular\cli\models\command-runner.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\@angular\cli\lib\cli\index.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\@angular\cli\lib\init.js
[ng] - D:\WS\Ionic\ionic4-starter-app\node_modules\@angular\cli\bin\ng
[ng]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
[ng]     at Function.Module._load (internal/modules/cjs/loader.js:527:27)
[ng]     at Module.require (internal/modules/cjs/loader.js:681:19)
[ng]     at require (internal/modules/cjs/helpers.js:16:16)
[ng]     at Object.sassLoader (D:\WS\Ionic\ionic4-starter-app\node_modules\sass-loader\lib\loader.js:46:72)
[ng] chunk {common} common.js, common.js.map (common) 21.6 kB  [rendered]
[ng] chunk {main} main.js, main.js.map (main) 33.6 kB [initial] [rendered]
[ng] chunk {pages-home-home-module} pages-home-home-module.js, pages-home-home-module.js.map (pages-home-home-module) 6.8 kB [rendered]
[ng] chunk {pages-new-item-new-item-module} pages-new-item-new-item-module.js, pages-new-item-new-item-module.js.map (pages-new-item-new-item-module) 10.5 kB  [rendered]
[ng] chunk {pages-update-item-update-item-module} pages-update-item-update-item-module.js, pages-update-item-update-item-module.js.map (pages-update-item-update-item-module) 11.3 kB  [rendered]
[ng] chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 236 kB [initial] [rendered]
[ng] chunk {runtime} runtime.js, runtime.js.map (runtime) 9 kB [entry] [rendered]
[ng] chunk {styles} styles.js, styles.js.map (styles) 23.1 kB [initial] [rendered]
[ng] chunk {vendor} vendor.js, vendor.js.map (vendor) 4.26 MB [initial] [rendered]
[ng] i ｢wdm｣: Failed to compile.

**Comment by djabif** [comment]
Can you please try this https://stackoverflow.com/questions/48147896/error-in-cannot-find-module-node-sass ?

**Comment by djabif** [comment]
@farahjr can I close this?
